name: Build Assets

on:
  push:
    branches:
      - main

jobs:
  build-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build assets
        run: npm run build
      - name: Deploy JS assets
        uses: cloudflare/wrangler-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        with:
          wranglerVersion: "3.93.0"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            r2 object put ${{ vars.BUCKET_NAME }}/js/app.js --file public/js/app.js --ct text/javascript --cache-control="public,max-age=3600"
            r2 object put ${{ vars.BUCKET_NAME }}/js/admin.js --file public/js/admin.js --ct text/javascript --cache-control="public,max-age=3600"
            r2 object put ${{ vars.BUCKET_NAME }}/css/main.css --file public/css/main.css --ct text/css --cache-control="public,max-age=3600"
